"""Build the hedge-capacity options panel (options_panel.csv).

Pipeline
--------
1. Fetch the raw chain JSONs from ThetaData (if needed, run scripts/02_fetch_chains.py).
2. Load the cached chain CSVs (generated by scripts/03_concat_screen.py).
3–7. Screen, duration-map, rate-space Greeks, hedge capacity, merge, IV join.
8. Write options_panel.csv.

Steps 3–7 are handled by ``src.data.options_panel.build_options_panel``,
which can also be called directly from a notebook cell.

Usage
-----
    python scripts/06_build_options_panel.py
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd

from src import config as cfg
from src.data.options_panel import build_options_panel
from src.data.options_universe import UNIVERSE

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    args = p.parse_args()

    logger.info("Loading core panel from %s …", cfg.CORE_PANEL_CSV)
    core_df = pd.read_csv(cfg.CORE_PANEL_CSV, parse_dates=["Date"])
    logger.info("  %d rows, %d tickers", len(core_df), core_df["Symbol"].nunique())

    build_options_panel(core_df, chains_df=None, write_csv=True)


if __name__ == "__main__":
    main()
